### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by lnicola**
- fix compile warnings
 - switch to the 2018 edition
 - bump some deps
 - use `std::fs::read_to_string`

### CODE REVIEW

**Comment by michaelbeaumont** [comment]
can you rebase? Just `cargo fmt`ed everything

**Comment by lnicola** [comment]
Rebased (I don't think there were conflicts anyway), but your GitHub CI workflow is set to run on push, not PRs, so it won't trigger here, and I don't know what the style check is.

**Comment by michaelbeaumont** [comment]
Indeed, the `style` status check is nonsense but it's the only one GH offers for enforcement. That appears to be some kind of bug. The proper github workflow should be there...

I don't _think_ the `pull_request` event is the issue. I can see it ran in your repo (it will always run only in your repo, because it's a fork), but I don't see the status for the commit here. It's not reporting the status at all, it should also do so when using `push`. You can try editing the workflow in your branch and adding `pull_request`.

**Comment by lnicola** [comment]
It seems fine now. I changed the workflow definition a bit.

**Comment by lnicola** [comment]
I guess it was running on _push_ in my fork instead.

I haven't used GitHub Actions much, but I settled on `actions-rs/cargo` instead. It's a bit nicer, e.g. in the standard Linux image the Rust compiler is already installed, while the one you're using is a Docker image and takes a minute to update.

You can see an example here: https://github.com/lnicola/sd-notify/blob/master/.github/workflows/ci.yml.

**Comment by michaelbeaumont** [comment]
Weird, under branch protection I still only see the following:

Status checks found in the last week for this repository
- [ ] style 

 :man_shrugging:

**Comment by michaelbeaumont** [comment]
ok, sounds good. I swiped the other one from https://github.com/tokio-rs/tracing/blob/master/.github/workflows/CI.yml

**Pull request merged**
